ARG NODE_IMAGE=node:20.11.0-alpine

FROM $NODE_IMAGE AS base
RUN mkdir -p /home/node/app && chown node:node /home/node/app
WORKDIR /home/node/app
USER node

FROM base AS dependencies
COPY --chown=node:node ./package*.json ./
RUN npm ci
COPY --chown=node:node . .

FROM dependencies AS build
RUN ADAPTER=node npm run build

FROM base AS production
COPY --chown=node:node ./package*.json .
RUN npm ci --omit dev
COPY --chown=node:node --from=build /home/node/app/build .

CMD ["node", "."]
