#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $POSTGRES_CUSTOM_USER WITH PASSWORD '$POSTGRES_CUSTOM_PASSWORD';
	CREATE DATABASE $POSTGRES_CUSTOM_DATABASE;
	GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_CUSTOM_DATABASE TO $POSTGRES_CUSTOM_USER;
  ALTER DATABASE $POSTGRES_CUSTOM_DATABASE OWNER TO $POSTGRES_CUSTOM_USER;
EOSQL
