name: frontend-ci

on:
  push:
    workflow_dispatch:
    branches: ["master", "testing"]
    tags:
      - "v*"
    paths:
      - frontend/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./**/package-lock.json"

      - name: Install common dependencies
        run: cd common; npm ci

      - name: Build common
        run: cd common; npm run build --if-present

      - name: Install frontend dependencies
        run: cd frontend; npm ci

      - name: Build frontend
        run: cd frontend; npm run build --if-present

  docker:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: cr.likablehair.it
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Docker meta frontend
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            cr.likablehair.it/mufasa_frontend
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          file: frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
